---
params:
  inputData: NA
---

<!-- load_all will recognize change -->

<!-- params = list(obj = ~~~) -->
<!-- obj <- params$obj -->

```{r, echo = FALSE}
inputData <- params$inputData
library(ggplot2)
library(ggpie)
library(GGally)
library(naniar)
```

## Data information

Number of Row with given data is `r nrow(inputData)` 

Number of Column with given data is `r ncol(inputData)` 

Total Count of missing data is `r length(which(is.na(inputData)))`

## Preview of data set

top 5 data is below

```{r, echo = FALSE}
head(inputData, 5)
```

last 5 data is below

```{r, echo = FALSE}
tail(inputData, 5)
```

### MissingData

```{r, echo = FALSE, warning = FALSE, message = FALSE}
naniar::gg_miss_var(inputData)
missingData <- naniar::miss_var_summary(inputData) %>% filter(n_miss > 0)
knitr::kable(missingData)
```


### Correlation

```{r, echo = FALSE, warning = FALSE, message = FALSE}
ggcorr(inputData)
```

### Distribution

```{r, results='asis', echo = FALSE, warning = FALSE, message = FALSE}
output <- vector('list', ncol(inputData))
for(i in 1:ncol(inputData)) {
  output[[i]] <- local({
    i <- i
    fig <-ggplot(data=inputData, aes(x=inputData[[i]])) + geom_histogram(fill="skyblue",colour="black") + xlab("value") + theme(legend.position = "none")
  })
}


for(i in 1:ncol(inputData)) {
cat("\n\n ", names(inputData)[i], "\n\n")
x <- output[[i]]
print(x)
cat("\n\n")
}
```


## Report information

this report is generated with [Statgarten](https://github.com/statgarten) @ `r Sys.time()`

