name: Dispatch update to statgarten/dockerImage

on: [push]

jobs:
  update-dockerImage:
    name: "Dispatch update to statgarten/dockerImage"
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: |
          echo "date=v$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: Send Trigger
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.dockerImage_CICD_SECRET }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/statgarten/dockerImage/dispatches \
            -d '{"event_type": "statgarten_update", "client_payload": {"tag": "${{ env.date }}" }}'
